### ISSUE TITLE
Add type "event" to ActivityType enums

### ISSUE THREAD

**Issue by akinmail** [antonleliuk/spring-social-botFramework#20]
Right now, unknown type is used for handling "event" types sent from directline channel, event type is a very popular type of Activity type. Adding this though, will break code previously written that checks for unknown type as a replacement for event that was previously unavailable.

**Comment by antonleliuk** [comment]
According [documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-activities), there are no such type in ActivityType

**Comment by akinmail** [comment]
Ok, that's fine just that this [documentation](https://github.com/Microsoft/BotFramework-WebChat) for directline usage from webchannel. It says you can set type as event.
`const postButtonMessage = () => {
    botConnection
        .postActivity({ type: "event", value: "", from: { id: "me" }, name: "buttonClicked" })
        .subscribe(id => console.log("success"));
    }
`

I think sticking with what's in the docs you sent is fine.

**Comment by antonleliuk** [comment]
For DirectLine we have separate module, but its still under construction
